AWSTemplateFormatVersion: "2010-09-09"


Description: >
  This template sets up the infrastructure.

Parameters:
  BuildNumber:
    Default: "1"
    Description: "build number"
    Type: String
    MinLength: 1
    ConstraintDescription: "is required"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: "Pipeline settings"
        Parameters:
          - BuildNumber

    ParameterLabels:
      BuildNumber:
        default: "BuildNumber"

Resources:


  # --- BEGIN INFRASTRUCTURE ---


  MyLambda:
    Type: AWS::Lambda::Function
    Properties:
      PackageType: "Image"
      Code:
        ImageUri: !Sub "760507411025.dkr.ecr.us-east-1.amazonaws.com/lambda-scrape:202405211517"
      ImageConfig:
        Command: ["lambda_functions.LF_extract.my_handler"]
      MemorySize: 4000
      EphemeralStorage:
        Size: 4000
      Role: "arn:aws:iam::760507411025:role/LabRole"
      Timeout: 900

  # --- END INFRASTRUCTURE ---